name: App request
description: Request an app on GitHub be added to Atlas-DB
labels: ["app request"]
assignees: ["venkeyz"]
body:
  - type: markdown
    attributes:
      value: "**Please ensure your app complies with the [Atlas-DB guidelines](https://github.com/atlorp/atlas-db/blob/master/CONTRIBUTING.md#app-requests) before submitting a request.**"
  - type: markdown
    attributes:
      value: "Go to [the app request web page](https://atlorp.github.io/atlas-db/app-request) and fill out the form to create a JSON for submission then come back here to submit it. Note that rarely used features are currently missing from the form, see [the wiki](https://github.com/Universal-Team/db/wiki/App-Template) for more information."
  - type: markdown
    attributes:
      value: "Know how to use git? Consider submitting a pull request to save time. (we use a script to handle issues but it takes a while)"
  - type: textarea
    attributes:
      label: Submission form
      description: Upload your JSON file here. You can also upload screenshots here.
      placeholder: You can drag drop the file into the text area or click the text below it.
