# theme       : jekyll-theme-slate
title       : "VenDB"
description : "VenDB - A unrestricted database of DS and 3DS homebrew"
repo        : "venkeyz/vendb"
color       : "#1d8056"
image       : "https://universal-team.net/images/icons/universal-team.png"

sass:
  sass_dir: _sass

collections:
  3ds:
    output: true
  ds:
    output: true
