# theme       : jekyll-theme-slate
title       : "Atlas-DB"
description : "Atlas-DB - An unrestricted database of DS and 3DS homebrew"
repo        : "atlorp/atlas-db"
color       : "#1d8056"
image       : "https://universal-team.net/images/icons/universal-team.png"

sass:
  sass_dir: _sass

collections:
  3ds:
    output: true
  ds:
    output: true
  dsi:
    output: true
  new-3ds:
    output: true
